// The captured skeletons (src/bones/, generated by `bun run bones:capture`) and
// the one runtime tweak boneyard lacks: honour reduced motion (ADR-0015). The
// generated registry already applied boneyard.config.json.
import { configureBoneyard } from 'boneyard-js/react'
import '~/bones/registry'

if (
  typeof window !== 'undefined' &&
  window.matchMedia('(prefers-reduced-motion: reduce)').matches
) {
  configureBoneyard({ animate: 'solid' })
}
