// Rebuilds src/bones/registry.ts from every committed *.bones.json (ADR-0025 §4).
//
// The boneyard CLI writes the registry from the skeletons it captured in that
// run only, so a subset capture (`bun run bones:capture /charging/economy`)
// would drop every other page's skeletons from it: they'd fall back to a plain
// block in prod, silently. captureBones.ts calls this after the CLI succeeds.
//
// The output mirrors the CLI's own (boneyard-js/bin/cli.js, "Generate
// registry.js", React flavour), except that names are sorted, so the file
// doesn't reorder with capture order.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const BONES_SUFFIX = '.bones.json'
// The CLI's runtime keys, in its order: copied from the config into configureBoneyard().
const RUNTIME_KEYS = [
  'color',
  'darkColor',
  'animate',
  'shimmerColor',
  'darkShimmerColor',
  'speed',
  'shimmerAngle',
  'stagger',
  'transition',
  'boneClass',
] as const

/** The skeleton names with a bones file in `dir`, sorted. */
export function capturedSkeletons(dir: string): string[] {
  return readdirSync(dir)
    .filter((f) => f.endsWith(BONES_SUFFIX))
    .map((f) => f.slice(0, -BONES_SUFFIX.length))
    .sort()
}

/** The registry source the CLI would write for `names` under `config`. */
export function renderBonesRegistry(names: string[], config: Record<string, unknown>): string {
  const runtime: Record<string, unknown> = {}
  for (const k of RUNTIME_KEYS) if (config[k] !== undefined) runtime[k] = config[k]
  const hasRuntime = Object.keys(runtime).length > 0
  const safe = (name: string) => name.replace(/[^a-zA-Z0-9._-]/g, '_')
  const varName = (name: string) => `_${safe(name).replace(/[^a-zA-Z0-9]/g, '_')}`

  const lines = ['"use client"', '// Auto-generated by `npx boneyard-js build` — do not edit']
  lines.push("import { registerBones } from 'boneyard-js'")
  if (hasRuntime) lines.push("import { configureBoneyard } from 'boneyard-js/react'")
  lines.push('')
  for (const name of names) lines.push(`import ${varName(name)} from './${safe(name)}.bones.json'`)
  lines.push('')
  if (hasRuntime) {
    lines.push(`configureBoneyard(${JSON.stringify(runtime)})`)
    lines.push('')
  }
  lines.push('registerBones({')
  for (const name of names) lines.push(`  "${safe(name)}": ${varName(name)},`)
  lines.push('})')
  lines.push('')
  return lines.join('\n')
}

/** Rewrites `<root>/src/bones/registry.ts` from every bones file there; returns the names. */
export function writeBonesRegistry(root = process.cwd()): string[] {
  const config = JSON.parse(readFileSync(join(root, 'boneyard.config.json'), 'utf8')) as {
    out?: string
  } & Record<string, unknown>
  const dir = join(root, config.out ?? './src/bones')
  const names = capturedSkeletons(dir)
  writeFileSync(join(dir, 'registry.ts'), renderBonesRegistry(names, config))
  return names
}
