#!/usr/bin/env node
// Generates the favicon set in public/ from one inline definition: the
// Oceanview brand mark (a single off-center sail, matching
// src/components/Logo.tsx) in the accent blue #156cdd (sRGB of --brand
// oklch(0.56 0.18 256) in src/styles/app.css). Two variants: a transparent
// sail for browser favicons (svg/png/ico) and a white-backed sail inside the
// safe zone for apple-touch-icon + maskable android icons, where transparency
// would render black and the platform applies its own corner mask.
//
// Run via `pnpm favicons:generate`.

import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import pngToIco from 'png-to-ico'
import sharp from 'sharp'

const publicDir = resolve(dirname(fileURLToPath(import.meta.url)), '../public')

const TILE_BLUE = '#156cdd'

// The brand mark, drawn in a 0–32 space and shared with src/components/Logo.tsx:
// a single off-center, wind-filled sail, centered in the box.
const SAIL = 'M11 2L7 30Q15 28.5 25 27.5Q23.5 11 11 2Z'

// glyphScale 1 fits the sail in the 64px canvas with ~2px padding; < 1 shrinks
// + centers it further for maskable icons' 80% safe zone. A `background` makes
// the square opaque (required by apple-touch + maskable Android, which render
// transparency as black); pass null for browser favicons so the sail floats
// transparently on any tab.
function sailSvg({ background, glyphScale }) {
  const k = 2 * glyphScale
  const offset = (64 - 32 * k) / 2
  const bg = background ? `<rect width="64" height="64" fill="${background}"/>` : ''
  return `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
  <title>Oceanview</title>
  <!-- Oceanview brand mark: an off-center sail. Generated by scripts/generateFavicons.mjs -->
  ${bg}<g transform="translate(${offset} ${offset}) scale(${k})">
    <path fill="${TILE_BLUE}" d="${SAIL}"/>
  </g>
</svg>
`
}

// Browser favicons: sail on transparent (floats on the tab bar).
const browserIcon = sailSvg({ background: null, glyphScale: 1 })
// apple-touch + maskable Android: sail inside the 80% safe zone on an opaque
// white field.
const maskableIcon = sailSvg({ background: '#ffffff', glyphScale: 0.8 })

function renderPng(svg, size) {
  return sharp(Buffer.from(svg), { density: (72 * size) / 64 })
    .resize(size, size)
    .png()
    .toBuffer()
}

const png16 = await renderPng(browserIcon, 16)
const png32 = await renderPng(browserIcon, 32)

const outputs = [
  ['favicon.svg', browserIcon],
  ['favicon-16x16.png', png16],
  ['favicon-32x32.png', png32],
  ['favicon.ico', await pngToIco([png16, png32])],
  ['apple-touch-icon.png', await renderPng(maskableIcon, 180)],
  ['android-chrome-192x192.png', await renderPng(maskableIcon, 192)],
  ['android-chrome-512x512.png', await renderPng(maskableIcon, 512)],
]

for (const [name, data] of outputs) {
  writeFileSync(resolve(publicDir, name), data)
  console.log(`[generateFavicons] wrote public/${name}`)
}

// Magic-link email header: the transparent sail at 3× the ~48px display size.
// Served at /email-logo.png by the app + prod; the email derives this origin
// from the magic link itself. See src/emails/MagicLinkEmail.tsx.
const emailLogo = await renderPng(browserIcon, 144)
writeFileSync(resolve(publicDir, 'email-logo.png'), emailLogo)
console.log('[generateFavicons] wrote public/email-logo.png')
