#!/usr/bin/env node
// Generates the favicon set in public/ from one inline definition: the
// Videbacken placeholder brand mark (a bold "V" lettermark, matching
// src/components/Logo.tsx) in the muted-indigo accent #5E6AB7 (sRGB of --brand
// oklch(0.55 0.12 275) in src/styles/app.css). Two variants: a transparent
// mark for browser favicons (svg/png/ico) and a white-backed mark inside the
// safe zone for apple-touch-icon + maskable android icons, where transparency
// would render black and the platform applies its own corner mask.
//
// This is a placeholder lettermark, not final brand art — swap SVG_MARK below
// (and src/components/Logo.tsx) when real branding is ready.
//
// Run via `pnpm favicons:generate`.

import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import pngToIco from 'png-to-ico'
import sharp from 'sharp'

const publicDir = resolve(dirname(fileURLToPath(import.meta.url)), '../public')

const BRAND_INDIGO = '#5E6AB7'

// The brand mark, drawn in a 0–32 space and shared with src/components/Logo.tsx:
// a bold, centered "V" lettermark.
const MARK = 'M4 3L16 29L28 3L22 3L16 18L10 3Z'

// glyphScale 1 fits the mark in the 64px canvas with ~2px padding; < 1 shrinks
// + centers it further for maskable icons' 80% safe zone. A `background` makes
// the square opaque (required by apple-touch + maskable Android, which render
// transparency as black); pass null for browser favicons so the mark floats
// transparently on any tab.
function markSvg({ background, glyphScale }) {
  const k = 2 * glyphScale
  const offset = (64 - 32 * k) / 2
  const bg = background ? `<rect width="64" height="64" fill="${background}"/>` : ''
  return `<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 64 64">
  <title>Videbacken</title>
  <!-- Videbacken placeholder brand mark: a "V" lettermark. Generated by scripts/generateFavicons.mjs -->
  ${bg}<g transform="translate(${offset} ${offset}) scale(${k})">
    <path fill="${BRAND_INDIGO}" d="${MARK}"/>
  </g>
</svg>
`
}

// Browser favicons: mark on transparent (floats on the tab bar).
const browserIcon = markSvg({ background: null, glyphScale: 1 })
// apple-touch + maskable Android: mark inside the 80% safe zone on an opaque
// white field.
const maskableIcon = markSvg({ background: '#ffffff', glyphScale: 0.8 })

function renderPng(svg, size) {
  return sharp(Buffer.from(svg), { density: (72 * size) / 64 })
    .resize(size, size)
    .png()
    .toBuffer()
}

const png16 = await renderPng(browserIcon, 16)
const png32 = await renderPng(browserIcon, 32)

const outputs = [
  ['favicon.svg', browserIcon],
  ['favicon-16x16.png', png16],
  ['favicon-32x32.png', png32],
  ['favicon.ico', await pngToIco([png16, png32])],
  ['apple-touch-icon.png', await renderPng(maskableIcon, 180)],
  ['android-chrome-192x192.png', await renderPng(maskableIcon, 192)],
  ['android-chrome-512x512.png', await renderPng(maskableIcon, 512)],
]

for (const [name, data] of outputs) {
  writeFileSync(resolve(publicDir, name), data)
  console.log(`[generateFavicons] wrote public/${name}`)
}

// Magic-link email header: the transparent mark at 3× the ~48px display size.
// Served at /email-logo.png by the app + prod; the email derives this origin
// from the magic link itself. See src/emails/MagicLinkEmail.tsx.
const emailLogo = await renderPng(browserIcon, 144)
writeFileSync(resolve(publicDir, 'email-logo.png'), emailLogo)
console.log('[generateFavicons] wrote public/email-logo.png')
