"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

configureBoneyard({"animate":"pulse","color":"#ebebeb","darkColor":"#262626"})

registerBones({
})
