"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _charging_chart from './charging-chart.bones.json'
import _charging_economy from './charging-economy.bones.json'
import _charging_patterns from './charging-patterns.bones.json'
import _charging_sessions from './charging-sessions.bones.json'
import _charging_sources from './charging-sources.bones.json'
import _charging_tariffs from './charging-tariffs.bones.json'
import _charging_timeline from './charging-timeline.bones.json'
import _charging_totals from './charging-totals.bones.json'
import _energy_chart from './energy-chart.bones.json'
import _energy_tiles from './energy-tiles.bones.json'

configureBoneyard({"color":"#ebebeb","darkColor":"#262626","animate":"pulse"})

registerBones({
  "charging-chart": _charging_chart,
  "charging-economy": _charging_economy,
  "charging-patterns": _charging_patterns,
  "charging-sessions": _charging_sessions,
  "charging-sources": _charging_sources,
  "charging-tariffs": _charging_tariffs,
  "charging-timeline": _charging_timeline,
  "charging-totals": _charging_totals,
  "energy-chart": _energy_chart,
  "energy-tiles": _energy_tiles,
})
