/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignedInRouteImport } from './routes/signed-in'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiLogRouteImport } from './routes/api/log'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSensorsRouteImport } from './routes/_authenticated/sensors'
import { Route as AuthenticatedChargingRouteImport } from './routes/_authenticated/charging'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as ApiWebhooksShellyRouteImport } from './routes/api/webhooks/shelly'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiCronZaptecSyncRouteImport } from './routes/api/cron/zaptec-sync'
import { Route as ApiCronGridTariffCatalogueRouteImport } from './routes/api/cron/grid-tariff-catalogue'
import { Route as ApiCronElprisSyncRouteImport } from './routes/api/cron/elpris-sync'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account/profile'

const SignedInRoute = SignedInRouteImport.update({
  id: '/signed-in',
  path: '/signed-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiLogRoute = ApiLogRouteImport.update({
  id: '/api/log',
  path: '/api/log',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSensorsRoute = AuthenticatedSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChargingRoute = AuthenticatedChargingRouteImport.update({
  id: '/charging',
  path: '/charging',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const ApiWebhooksShellyRoute = ApiWebhooksShellyRouteImport.update({
  id: '/api/webhooks/shelly',
  path: '/api/webhooks/shelly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronZaptecSyncRoute = ApiCronZaptecSyncRouteImport.update({
  id: '/api/cron/zaptec-sync',
  path: '/api/cron/zaptec-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronGridTariffCatalogueRoute =
  ApiCronGridTariffCatalogueRouteImport.update({
    id: '/api/cron/grid-tariff-catalogue',
    path: '/api/cron/grid-tariff-catalogue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronElprisSyncRoute = ApiCronElprisSyncRouteImport.update({
  id: '/api/cron/elpris-sync',
  path: '/api/cron/elpris-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signed-in': typeof SignedInRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/charging': typeof AuthenticatedChargingRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/log': typeof ApiLogRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/elpris-sync': typeof ApiCronElprisSyncRoute
  '/api/cron/grid-tariff-catalogue': typeof ApiCronGridTariffCatalogueRoute
  '/api/cron/zaptec-sync': typeof ApiCronZaptecSyncRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/shelly': typeof ApiWebhooksShellyRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signed-in': typeof SignedInRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/charging': typeof AuthenticatedChargingRoute
  '/sensors': typeof AuthenticatedSensorsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/log': typeof ApiLogRoute
  '/': typeof AuthenticatedIndexRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/elpris-sync': typeof ApiCronElprisSyncRoute
  '/api/cron/grid-tariff-catalogue': typeof ApiCronGridTariffCatalogueRoute
  '/api/cron/zaptec-sync': typeof ApiCronZaptecSyncRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/shelly': typeof ApiWebhooksShellyRoute
  '/account': typeof AuthenticatedAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signed-in': typeof SignedInRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/charging': typeof AuthenticatedChargingRoute
  '/_authenticated/sensors': typeof AuthenticatedSensorsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/log': typeof ApiLogRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/elpris-sync': typeof ApiCronElprisSyncRoute
  '/api/cron/grid-tariff-catalogue': typeof ApiCronGridTariffCatalogueRoute
  '/api/cron/zaptec-sync': typeof ApiCronZaptecSyncRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/webhooks/shelly': typeof ApiWebhooksShellyRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signed-in'
    | '/account'
    | '/admin'
    | '/charging'
    | '/sensors'
    | '/users'
    | '/api/log'
    | '/account/profile'
    | '/api/auth/$'
    | '/api/cron/elpris-sync'
    | '/api/cron/grid-tariff-catalogue'
    | '/api/cron/zaptec-sync'
    | '/api/rpc/$'
    | '/api/webhooks/shelly'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/signed-in'
    | '/admin'
    | '/charging'
    | '/sensors'
    | '/users'
    | '/api/log'
    | '/'
    | '/account/profile'
    | '/api/auth/$'
    | '/api/cron/elpris-sync'
    | '/api/cron/grid-tariff-catalogue'
    | '/api/cron/zaptec-sync'
    | '/api/rpc/$'
    | '/api/webhooks/shelly'
    | '/account'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/signed-in'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/charging'
    | '/_authenticated/sensors'
    | '/_authenticated/users'
    | '/api/log'
    | '/_authenticated/'
    | '/_authenticated/account/profile'
    | '/api/auth/$'
    | '/api/cron/elpris-sync'
    | '/api/cron/grid-tariff-catalogue'
    | '/api/cron/zaptec-sync'
    | '/api/rpc/$'
    | '/api/webhooks/shelly'
    | '/_authenticated/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignedInRoute: typeof SignedInRoute
  ApiLogRoute: typeof ApiLogRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronElprisSyncRoute: typeof ApiCronElprisSyncRoute
  ApiCronGridTariffCatalogueRoute: typeof ApiCronGridTariffCatalogueRoute
  ApiCronZaptecSyncRoute: typeof ApiCronZaptecSyncRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiWebhooksShellyRoute: typeof ApiWebhooksShellyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signed-in': {
      id: '/signed-in'
      path: '/signed-in'
      fullPath: '/signed-in'
      preLoaderRoute: typeof SignedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/log': {
      id: '/api/log'
      path: '/api/log'
      fullPath: '/api/log'
      preLoaderRoute: typeof ApiLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sensors': {
      id: '/_authenticated/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof AuthenticatedSensorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/charging': {
      id: '/_authenticated/charging'
      path: '/charging'
      fullPath: '/charging'
      preLoaderRoute: typeof AuthenticatedChargingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/api/webhooks/shelly': {
      id: '/api/webhooks/shelly'
      path: '/api/webhooks/shelly'
      fullPath: '/api/webhooks/shelly'
      preLoaderRoute: typeof ApiWebhooksShellyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/zaptec-sync': {
      id: '/api/cron/zaptec-sync'
      path: '/api/cron/zaptec-sync'
      fullPath: '/api/cron/zaptec-sync'
      preLoaderRoute: typeof ApiCronZaptecSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/grid-tariff-catalogue': {
      id: '/api/cron/grid-tariff-catalogue'
      path: '/api/cron/grid-tariff-catalogue'
      fullPath: '/api/cron/grid-tariff-catalogue'
      preLoaderRoute: typeof ApiCronGridTariffCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/elpris-sync': {
      id: '/api/cron/elpris-sync'
      path: '/api/cron/elpris-sync'
      fullPath: '/api/cron/elpris-sync'
      preLoaderRoute: typeof ApiCronElprisSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedChargingRoute: typeof AuthenticatedChargingRoute
  AuthenticatedSensorsRoute: typeof AuthenticatedSensorsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedChargingRoute: AuthenticatedChargingRoute,
  AuthenticatedSensorsRoute: AuthenticatedSensorsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignedInRoute: SignedInRoute,
  ApiLogRoute: ApiLogRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronElprisSyncRoute: ApiCronElprisSyncRoute,
  ApiCronGridTariffCatalogueRoute: ApiCronGridTariffCatalogueRoute,
  ApiCronZaptecSyncRoute: ApiCronZaptecSyncRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiWebhooksShellyRoute: ApiWebhooksShellyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
