import type { Locale } from '~/paraglide/runtime'
import { lazy } from '../lazy'

/**
 * Email interface backed by one of three adapters:
 *   - `smtp` — nodemailer SMTP transport. Selected when `SMTP_HOST` is set;
 *     used in local dev to send through the Mailpit container (compose
 *     service `mail`). Takes precedence over `RESEND_API_KEY` so a stray
 *     `vercel env pull` doesn't route dev sends through the real Resend
 *     account.
 *   - `resend` — Resend SDK. Selected when `RESEND_API_KEY` is set and
 *     `SMTP_HOST` is not — i.e. production.
 *   - `devLog` — logs to the structured logger. Used in tests (VITEST
 *     short-circuit) and as the offline fallback when neither SMTP nor
 *     Resend is configured.
 *
 * Adapters render the React Email template internally and hand
 * `{ subject, html, text }` to their transport. Procedures and auth
 * callbacks (`src/lib/auth.ts`) call this interface; they never import
 * a transport or template directly.
 *
 * Magic-link send stays sync-critical (tier-1 per ADR-0001). Future
 * non-auth emails (user invitations, schedule reminders, digests) will
 * be invoked from the queue (tier-3) — same adapter, different caller.
 * See ADR-0008.
 */
export interface EmailEffects {
  sendMagicLink(input: { to: string; url: string; locale: Locale }): Promise<void>
  // User invitation (tier-3): the verify-email link is generated by Better
  // Auth and delivered via the `email_user_invited` queue topic, so the worker
  // calls this. `inviteUrl` is the verify-email link; clicking it accepts the
  // invite (verifies + auto-signs-in). See ADR-0008/0017.
  sendUserInvited(input: { to: string; inviteUrl: string; locale: Locale }): Promise<void>
}

const getAdapter = lazy(async (): Promise<EmailEffects> => {
  if (process.env.VITEST === 'true') return (await import('./adapters/devLog')).devLog
  if (process.env.EMAIL_ADAPTER === 'devLog') return (await import('./adapters/devLog')).devLog
  if (process.env.SMTP_HOST) return (await import('./adapters/smtp')).smtp
  if (process.env.RESEND_API_KEY) {
    if (process.env.EMAIL_FROM) return (await import('./adapters/resend')).resend
    // Half-configured Resend (API key set, EMAIL_FROM forgotten) would throw
    // on every send — and magic-link is tier-1, so that bricks sign-in
    // entirely. Fall back to devLog (links in Runtime Logs, same as the
    // pre-DNS deferred state) and complain loudly instead.
    const { logger } = await import('~/lib/logger/server')
    logger.error('RESEND_API_KEY is set but EMAIL_FROM is missing; falling back to devLog')
    return (await import('./adapters/devLog')).devLog
  }
  return (await import('./adapters/devLog')).devLog
})

export const email: EmailEffects = {
  async sendMagicLink(input) {
    const adapter = await getAdapter()
    return adapter.sendMagicLink(input)
  },
  async sendUserInvited(input) {
    const adapter = await getAdapter()
    return adapter.sendUserInvited(input)
  },
}
